version: '2'
services:
  nginx:
    container_name: nginx
    image: nginx:1.12-alpine
    ports:
      - 8080:80
    volumes:
      - ./build:/usr/share/nginx/html
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
  couchdb:
    container_name: couch
    image: couchdb
    ports:
      - 5984:5984
    volumes:
      - /usr/local/var/lib/couchdb
